name: Full Continuous Integration

on: [push, pull_request]

jobs:
  pack:
    name: Build
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release --no-build -v normal
        shell: bash # defaults disagree on how to quote the filter string

      - name: Pack
        run: dotnet pack -c Release --no-build -o artifacts -p:NoWarn=NU5105

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: NuGet Package Files
          path: artifacts

  uploadToGithub:
    name: Upload to Github package registry
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    needs: pack
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    steps:
      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Download Package Files
        uses: actions/download-artifact@v3
        with:
          name: NuGet Package Files
          path: artifacts

      - name: Publish Package Files to Github
        run: dotnet nuget push artifacts/*.nupkg -s https://nuget.pkg.github.com/avinet/index.json -k $GITHUB_API_KEY
        shell: bash
        env:
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
